// All on-screen copy in one place, so the video can be re-worded or translated
// without touching the animation code. `<em>` = highlighted (sky blue) part of a headline.
export const COPY = {
  intro: {
    kicker: 'AI Control Layer',
    tagline: 'Fence. Redact. Protect. Log.',
    sticker: 'rawr.',
  },
  problem: {
    headline: 'AI agents talk to <em>everything.</em>',
    turn: 'Time to bring out <em>the claws.</em>',
    agent: 'AI agent',
    nodes: ['LLMs', 'MCP tools', 'Internal APIs', 'Customer data'],
    threats: ['Prompt injection', 'Leaked secrets', 'Jailbreaks', 'PII leakage', 'Rogue tool calls', 'Runaway token spend'],
  },
  dropIn: {
    num: '01',
    kicker: 'Drop-in gateway',
    headline: 'One line. <em>Zero rewrites.</em>',
    sub: 'Point any SDK at clawGS. It speaks OpenAI, Anthropic and Gemini natively.',
    newUrl: 'https://clawgs.corp/v1',
    badge: 'Every call now passes through clawGS',
    protocols: [
      ['OpenAI', 'POST /v1/chat/completions'],
      ['Anthropic', 'POST /v1/messages'],
      ['Gemini', 'POST /v1beta/models/…:generateContent'],
      ['Streaming', 'SSE on all three protocols'],
      ['Local models', 'Ollama & more via LiteLLM'],
    ],
  },
  guardrails: {
    num: '02',
    kicker: 'Hybrid guardrails',
    headline: 'Deterministic speed. <em>Semantic brains.</em>',
    sub: 'Rules catch the obvious. An AI decision model catches the sneaky. Before and after the LLM.',
    feedTitle: 'Verdicts',
    feedNote: 'global + per-key policy chains · fast-fail',
    dmTitle: 'Decision model',
    dmQuestion: '“Does this try to get around the rules?”',
    dmScore: 'risk score',
    keywordMiss: 'no keyword match',
  },
  blocks: {
    num: '03',
    kicker: 'Block responses',
    headline: 'Blocked, <em>not broken.</em>',
    sub: 'Agents get a polite, protocol-native reply, streaming included, so nothing crashes.',
    message: 'Blocked by policy.',
    chips: ['HTTP 200, valid schema', 'SSE streams too', 'Custom templates per model & MCP server'],
  },
  mcp: {
    num: '04',
    kicker: 'MCP firewall',
    headline: 'Agents only touch <em>the tools you allow.</em>',
    sub: 'Tool whitelists and MCP-aware policies on every JSON-RPC call.',
    server: 'github-mcp',
    serverNote: 'MCP server · 4 tools',
    allowed: 'whitelisted',
    denied: 'not whitelisted',
  },
  budgets: {
    num: '05',
    kicker: 'Budgets & rate limits',
    headline: 'Budgets <em>that bite.</em>',
    sub: 'Hard spend caps and requests-per-minute limits per API key. Cost centers for chargeback.',
    keyName: 'research-agent',
    costCenter: 'Cost center · Research',
    budgetLabel: 'Spend this month',
    rateTitle: 'Rate limit',
    rateChip: '60 req / min',
    rateNote: 'sliding 60 s window · Redis-backed',
  },
  reporting: {
    num: '06',
    kicker: 'Security reporting',
    headline: 'Every verdict, <em>on the record.</em>',
    sub: 'Live audit trail for security teams, real-time posture for management. Load-tested on 1,000,000 logs.',
  },
  essentials: {
    num: '07',
    kicker: 'Batteries included',
    headline: 'Plus everything <em>you’d expect.</em>',
    tiles: [
      ['database', 'Models', 'Allow-list, cost centers & default routing'],
      ['server', 'MCP Servers', 'Register servers, sync & whitelist tools'],
      ['key-round', 'Provider Keys', 'Upstream API keys, encrypted at rest'],
      ['users', 'Users', 'Admin & AI-owner roles'],
      ['lock-keyhole', 'SSO Providers', 'Any OpenID Connect identity provider'],
      ['webhook', 'Webhooks', 'Real-time SECURITY_BLOCK alerts'],
      ['history', 'System Audit', 'Every admin change, on record'],
      ['download', 'Data Export', 'CSV & JSON for your SIEM'],
    ],
  },
  outro: {
    line: 'The AI control layer <em>with claws.</em>',
    tagline: 'Fence. Redact. Protect. Log.',
    sticker: 'rawr.',
  },
};
